config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end
  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
      @movies = Movie.released
    end
    def show
      @movie = Movie.find(params[:id])
    end
    def edit
      @movie = Movie.find(params[:id])
    end
    def update
      @movie = Movie.find(params[:id])
      @movie.update(movie_params)
      redirect_to @movie
    end
    def new
      @movie = Movie.new
    end
    
    def create
      @movie = Movie.new(movie_params)
      @movie.save
      redirect_to @movie
    end

    def destroy
      @movie = Movie.find(params[:id])
      @movie.destroy
      redirect_to movies_url, status: :see_other
    end

    private

    def movie_params
      params.require(:movie).permit(:title, :description, :rating, :released_on,
                     :total_gross, :director, :duration, :image_file_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

    def total_gross(movie)
      if movie.flop?
        "Flop!"
      else
        number_to_currency(movie.total_gross, precision: 0)
      end
    end

    def year_of(movie)
      movie.released_on.year
    end

end

app/views/layouts/_footer.html.erb
    <footer>
      Copyright &copy <%= Time.now.year %>
      <%= link_to "Atchity Enterprises", "http://atchity.net" %>
    </footer>

app/views/layouts/_header.html.erb
    <header>
      <nav>
        <%= link_to image_tag("logo.png"), root_path %>
        <ul>
          <li>
            <%= link_to "All Movies", movies_path %>
          </li>
        </ul>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% AutoprefixerRails.uninstall(Rails.application.assets) %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 10 %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.label :released_on %>
  <%= f.date_select :released_on, {}, {class: "date"} %>

  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <%= f.label :duration %>
  <%= f.text_field :duration %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.submit %>

<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie|  %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>

app/views/movies/new.html.erb
<h1>Create a New Movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
  </div>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2><%= year_of(@movie) %> &bull; <%= @movie.rating %></h2>
    <p>
      <%= @movie.description %>
    </p>

    <table>
      <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_movie_path, class: "button" %>
  <%= link_to "Delete", @movie, class: "button", data: { turbo_method: :delete, turbo_confirm: "Really?"} %>
</section>